-- MySQL Script generated by MySQL Workbench
-- Sat Mar  3 14:40:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`store` (
  `store id` INT NOT NULL AUTO_INCREMENT,
  `adress` VARCHAR(100) NULL,
  `zipcode` INT NULL,
  PRIMARY KEY (`store id`),
  UNIQUE INDEX `store id_UNIQUE` (`store id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`intem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`intem` (
  `product-id` INT NOT NULL,
  `quantity in store` INT NULL,
  `exp-date` DATE NULL,
  `time added` TIME NULL,
  `product branch` VARCHAR(50) NULL,
  `store_store id` INT NOT NULL,
  PRIMARY KEY (`product-id`, `store_store id`),
  INDEX `fk_intem_store_idx` (`store_store id` ASC),
  CONSTRAINT `fk_intem_store`
    FOREIGN KEY (`store_store id`)
    REFERENCES `mydb`.`store` (`store id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sale` (
  `sale id` INT NOT NULL AUTO_INCREMENT,
  `price` FLOAT NULL,
  `type of sale` VARCHAR(45) NULL,
  `date of sale` DATE NULL,
  `time sale` TIME NULL,
  `store_store id` INT NOT NULL,
  PRIMARY KEY (`sale id`, `store_store id`),
  UNIQUE INDEX `sale id_UNIQUE` (`sale id` ASC),
  INDEX `fk_Sale_store1_idx` (`store_store id` ASC),
  CONSTRAINT `fk_Sale_store1`
    FOREIGN KEY (`store_store id`)
    REFERENCES `mydb`.`store` (`store id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
