# Generated by Django 2.0.4 on 2018-04-05 04:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('barcode', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Boxes',
            },
        ),
        migrations.CreateModel(
            name='BoxContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='littlebytes.Box')),
            ],
            options={
                'verbose_name_plural': 'Box Contents',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('date_exp', models.DateTimeField()),
                ('date_enter', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='littlebytes.Ingredient')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Sandwiches',
            },
        ),
        migrations.CreateModel(
            name='SandwichRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_amount', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='littlebytes.Ingredient')),
                ('sandwich', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='littlebytes.Sandwich')),
            ],
            options={
                'verbose_name_plural': 'Sandwich Recipes',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tax', models.DecimalField(decimal_places=3, max_digits=10)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(max_length=1)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='littlebytes.Box')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='littlebytes.Store')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='littlebytes.Store'),
        ),
        migrations.AddField(
            model_name='boxcontents',
            name='sandwich',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='littlebytes.Sandwich'),
        ),
    ]
