# Generated by Django 2.0.4 on 2018-04-08 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('littlebytes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='contents',
            field=models.ManyToManyField(through='littlebytes.BoxContents', to='littlebytes.Sandwich'),
        ),
        migrations.AddField(
            model_name='sandwich',
            name='ingredients',
            field=models.ManyToManyField(through='littlebytes.SandwichRecipe', to='littlebytes.Ingredient'),
        ),
        migrations.AddField(
            model_name='store',
            name='ingredients',
            field=models.ManyToManyField(through='littlebytes.Inventory', to='littlebytes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
