# Generated by Django 2.0.2 on 2018-02-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=1)),
                ('product', models.CharField(max_length=200)),
                ('stock', models.IntegerField(default=1)),
                ('perish_datetime', models.DateTimeField(blank=True, null=True)),
                ('datetime_added', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=1)),
                ('product_id', models.IntegerField(default=1)),
                ('consumer', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('consumed', models.IntegerField(default=1)),
                ('datetime_consumed', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
