# Generated by Django 2.0.2 on 2018-02-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('little_bytes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='datetime_consumed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
